import type { Metadata } from "next";
import "./govuk.scss";
import GovukInit from "./GovukInit";
import GovukHeader from "./components/GovukHeader";
import ServiceNavigation from "./components/ServiceNavigation";
import GovukFooter from "./components/GovukFooter";


export const metadata: Metadata = {
  title: "Civil Service Jobs",
  description: "next.js prototype for Civil Service Jobs.",
};

const navLinks = [
  { href: '/', text: 'Home', active: true },
  { href: '/jobs', text: 'View all jobs', active: false },
  { href: '/Cymraeg', text: 'Cymraeg', active: false },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="govuk-template govuk-template--rebranded">
      <body className="govuk-template__body">

        <GovukHeader />

        <ServiceNavigation links={navLinks} />

          <div className="govuk-width-container">
            <main className="govuk-main-wrapper" id="main-content" role="main">
                <GovukInit>{children}</GovukInit>         
            </main>
          </div>

        <GovukFooter />

      </body>
    </html>
  );
}

/* const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}
*/